### ISSUE TITLE
Prestashop support 

### ISSUE THREAD

**Issue by rrd108** [webmenedzser/uvb-connector#1]
Elég egyszerű az API, meg tudnám írni hozzá a prestashop modult.

**Comment by Saboteur777** [comment]
Az szuper lenne! Hogyan működik a prestashop ökoszisztéma? Ott is pluginok vannak?

**Comment by rrd108** [comment]
Igen ott is. Hasonlóan a wordpresshez persze totál más belső működéssel. Megnézem a wordpress plugint és kitaláljuk, hogyan valósítható meg prestashopban.

**Comment by Saboteur777** [comment]
Nagyon király! Szólj, ha kérdésed van (hívj, vagy írj, ahogy neked jobb)!

Csinálok egy staging-et, megírom, amikor elkészültem.

**Comment by Saboteur777** [comment]
Elkészültem a sandbox rendszerrel: https://sandbox.utanvet-ellenor.hu

Releváns commitok: 
- https://github.com/webmenedzser/uvb-connector/commit/8a7720e9f518795afcf95b616b754f68f4675027
- https://github.com/webmenedzser/uvb-connector-woocommerce/commit/289166b3be886caba73a21b60022f3f139940369

Frissítettem a dokumentációt is: https://github.com/webmenedzser/uvb-connector#sandbox-environment

Használhatod a már létező fiókotokat és API kulcsotokat, de hozzáadhatsz egy teljesen újat is. A sandbox rendszer minden reggel 4.00-kor visszaáll az éles rendszer egy korábbi verziójára, tehát idővel átszivárog az éles rendszeren eszközölt változtatás is.

Frissült az Integráció aloldal is: https://utanvet-ellenor.hu/integracio

**Comment by rrd108** [comment]
Köszi. Kell pár nap mire odajutok.

**Comment by rrd108** [comment]
![config](https://user-images.githubusercontent.com/3147489/102219927-68fdec00-3ee0-11eb-8192-1e233220aff0.jpg)

**Comment by Saboteur777** [comment]
Fú, hát ez nagyon jó! Ki tudom próbálni valahogy? 

A fenti angol szövegre egy kis javítást javaslok: 

> Customers with a reputation below the threshold will not be able to select Cash on Delivery as their preferred payment method. 
> This module helps you minimize the risk of sending out packages resulting in unsuccessful deliveries.

**Comment by rrd108** [comment]
> Fú, hát ez nagyon jó! Ki tudom próbálni valahogy?

Még csak annyi van, hogy elmentjük a config beállításokat, a lényeg hiányzik. Most csak 40 percem volt rá, reméljük a következő napokban jön a többi. Ha van tesztelhető verzió küldöm majd.

**Comment by Saboteur777** [comment]
Köszi! Github repóban dolgozol?

**Comment by rrd108** [comment]
> Köszi! Github repóban dolgozol?

Küldtem meghívót

**Comment by Saboteur777** [comment]
Köszönöm!

**Comment by rrd108** [comment]
Olyan vásárlókat beküldjünk az API-ba akik mondjuk bankkártyával fizettek? Az igen és a nem mellett is vannak érveim. Mit gondolsz? Mit csinál a woocommerce plugin?

**Comment by rrd108** [comment]
Elakadtam azon, hogy a prestashop guzzle 5-t használ, a conectorod meg 6-ot. Egy projekten belül nem tölthetünk be két verziót, így viszont nem tudok az apival kommunikálni. Próbáltam meghekkelni a connectort, egy guzzle-hoz hasonló csomaggal, de mindegyik megakadt valamin.

**Comment by rrd108** [comment]
> Elakadtam azon, hogy a prestashop guzzle 5-t használ, a conectorod meg 6-ot. Egy projekten belül nem tölthetünk be két verziót, így viszont nem tudok az apival kommunikálni. Próbáltam meghekkelni a connectort, egy guzzle-hoz hasonló csomaggal, de mindegyik megakadt valamin.

Beszereltem egy új csomagot, de jó lenne ha megmondanád, hogy pont mit vár az API, hogy reprodukálni tudjam a guzzle átalakításokat.
Ha url encoded formként küldök adatokat POST-ban az API-ra így:

```
> POST /api/v1/signals/ HTTP/2
> Host: sandbox.utanvet-ellenor.hu
> user-agent: insomnia/2020.5.1
> content-type: application/x-www-form-urlencoded
> accept: */*
> content-length: 200

auth%5B%5D=_public_key_&auth%5B%5D=_private_key_&json%5BemailHash%5D=_generated_hash_&json%5Boutcome%5D=1
```

Akkor 500-as HTTP hibát kapok
`Unknown error
Argument 1 passed to modules\utanvetellenorbackendmodule\helpers\SanitizerHelper::sanitizeKey() must be of the type string, null given, called in /var/www/modules/utanvetellenorbackendmodule/src/controllers/SignalsController.php on line 57`

**Comment by Saboteur777** [comment]
Bocs, az elmúlt másfél nap kicsit sűrű volt. A válaszok: 

1. Szerintem jöhet mindenki, a WP plugin jelenleg nem válogat. 
2. Frissítettem a connector-t, most már 5.3 és 6.3 feletti Guzzle is megfelel: https://github.com/webmenedzser/uvb-connector/commit/4f7312edc02fb212daf77c39815984cd82dafe0d
3. Az API HTTP Basic autentikációt használ (JSON és multipart is jöhet): 

![image](https://user-images.githubusercontent.com/9061795/102664830-ed23ce00-4183-11eb-8734-ca1ba9ca23b3.png)

Az 500-as hiba miatt van, hogy üres public/private API kulcsot küldesz, és ezt nem kezelem le megfelelően - ezt javítani fogom, köszi, hogy szóltál!

**Comment by rrd108** [comment]
Elkészültem a PS integrációval. Kicsit még kell csiszolni rajta, de szépen működik.

**Comment by rrd108** [comment]
A threshol tizedes pontot vár? Tizedes vesszővel nem bírkózik meg?

**Comment by Saboteur777** [comment]
Nagyon jó hír, köszönöm! Ránézek, amint tudok és visszajelzek. A tizedes vesszőt most már lekezeli a backend, de természetesen standard float-ot várna.

**Comment by rrd108** [comment]
> Nagyon jó hír, köszönöm! Ránézek, amint tudok és visszajelzek. A tizedes vesszőt most már lekezeli a backend, de természetesen standard float-ot várna.

Hm. Nálam az a tapasztalat, hogy ha tizedes vesszővel küldöm az adatot akkor az api hívás null-t ad vissza

**Comment by Saboteur777** [comment]
![image](https://user-images.githubusercontent.com/9061795/102710365-0e82d800-42b2-11eb-84ef-e5095839a23f.png)
![image](https://user-images.githubusercontent.com/9061795/102710382-28241f80-42b2-11eb-98c6-834886b82fc9.png)

Ránézek a PS integrációra, meglátom, mire jutok.

**Comment by rrd108** [comment]
Újra teszteltem én valóban nem a tizedes vesszővel van problémája, azt jól lekezeli, hanem az, hogy a status értéke 404.

```php
$reputation = json_decode($connector->get());
/*
{
  status: 404,
  message: {
    good: 63,
    bad: 85,
    ...
  }
}
*/
```

**Comment by Saboteur777** [comment]
Igen, mert ellenőrzöd a status értékét. Viszont akkor is adunk vissza választ, ha nincs találat, ezért szerintem arra ne ellenőrizz - a WooCommerce kiadás sem ellenőriz: 

https://github.com/webmenedzser/uvb-connector-woocommerce/blob/931b62e130e8dbb68ede46cdf9fbdc5cfae56bbe/public/class-uvb-connector-woocommerce-public.php#L140

Plusz érdemes lehet iterálás helyett közvetlenül unsetelni a kulcsot a `$paymentOptions` változóban, ha létezik a tömbben.

**Comment by rrd108** [comment]
ok. Kivettem az ellenőrzést.

Végig kell iterálnom, PS-ben fent lehet akár 5 féle COD modul egyszerre, és enélkül nem tudom melyik modul az és melyik nem az.

**Comment by Saboteur777** [comment]
Oké, akkor nem szóltam, köszi!

**Comment by rrd108** [comment]
Kész vagyok. Felteszed az utanvet-ellenor.hu oldalon az integrációk közé? https://github.com/rrd108/ps-utanvet-ellenor/tags

A hivatalos prestashop áruházba már nem lehet ingyenes modulokat feltenni, szóval oda nem kerül be. De ha megvagy akkor meghirdetném a ps csoportban.

**Comment by Saboteur777** [comment]
Nagyon örülök, köszönöm! 

A héten letesztelem, küldök hozzá néhány javítást, és természetesen felteszem az integrációk közé.

**Comment by Saboteur777** [comment]
Blocking issue: https://github.com/rrd108/ps-utanvet-ellenor/issues/6

**Comment by Saboteur777** [comment]
Kiadva. :partying_face: :tada: 

Felkerült az oldalra is: 
- https://utanvet-ellenor.hu/integracio
- https://utanvet-ellenor.hu/integracio/prestashop-integracio

**Comment by rrd108** [comment]
https://www.facebook.com/groups/prestashophu/permalink/5238269542880217

**Comment by rrd108** [comment]
Annyit kérhetek, hogy írd majd át alkalomadtán a Radharadhya das-t "rrd"-re?

**Comment by Saboteur777** [comment]
@rrd108 Átírtam. Köszi a FB posztot! :)
