### ISSUE TITLE
install hiba

### ISSUE THREAD

**Issue by rrd108** [webmenedzser/uvb-connector#2]
A plugin bekapcsolásakor ezt a hibát kapom

Warning: require(/home/rrd/public_html/bolt/wp-content/plugins/uv-b-connector-for-woocommerce/vendor/composer/platform_check.php): failed to open stream: No such file or directory in /home/rrd/public_html/bolt/wp-content/plugins/uv-b-connector-for-woocommerce/vendor/composer/autoload_real.php on line 25

Fatal error: require(): Failed opening required '/home/rrd/public_html/bolt/wp-content/plugins/uv-b-connector-for-woocommerce/vendor/composer/platform_check.php' (include_path='.:') in /home/rrd/public_html/bolt/wp-content/plugins/uv-b-connector-for-woocommerce/vendor/composer/autoload_real.php on line 25

**Comment by Saboteur777** [comment]
@rrd108 Javítottam, köszi! (SVN, doh... )
