### ISSUE TITLE
Flag orders if the customer reputation is around the threshold

### ISSUE THREAD

**Issue by rrd108** [webmenedzser/uvb-connector#3]
Szerintem érdemes lenne a rendelésben megjeleníteni a vásárló jelenlegi threshold-ját. Ez akkor lenne hasznos, ha ugyan felette van annak, mint amit beállítottam minimumként, és a rendszer engedte utánvéttel fizetni, de mondjuk egy határeset.
Így a webshopnak lenne gy jelzése, hogy érdemes a klienst felhívni csomag feladás előtt.

**Comment by Saboteur777** [comment]
Ha a "jelenlegi" alatt a rendeléskorit érted, akkor azt el lehet tenni a rendelés mellé, persze. Viszont ha ezt referencia implementációnak szánjuk Prestashop-hoz, akkor viszont én nem nagyon térnék el a WP-s plugin működésétől. Az ötlet viszont nem rossz, bevihetem a WP-s pluginbe is: mennyi ráhagyást hagyjunk? +/- 10%, tehát egy 0.7-es threshold esetén 0.68 - 0.77 között flagelné a rendelést, hogy kérdéses lehet. 

Viszont a user-hez semmiképpen sem menteném le "kliens oldalon" (értve itt a kliens alatt a webshopot).

**Comment by rrd108** [comment]
Én valami olyasmit csinálnék, hogy ahányszor belemegy a rendelésbe annyiszor lekéri ezt az API-tól. Mert simán lehet, hogy lead a vásárló nálam egy rendelést, akkor még nincs is rendszerben, de mire összecsomagolom már van egy-két át nem vett rendelése.
A woo-ba is jól jönne (nekünk is woo-s boltunk van), de a prestába is betenném.

Én valami olyasmit csinálnék, hogy van egy színátmenetes csík -1-től 1-ig, a -1 piros, a +1 zöld, rajta egy jel a beállított thresholddal és egy másik a vásárló aktuális értékével (már ha van). ez elég vizuális lenne. Esetleg egy tipp, vagy minősítés, hogy biztonságosnak tűnik / nótorius át nem vevő / inkább hívd fel mielőtt kiküdöd.

**Comment by Saboteur777** [comment]
Egyelőre érjünk el egy feature parity-t a prestás megoldással is, és utána bővíthetjük a funkcionalitást. A referencia implementációt nem bonyolítanám túl, valamilyen formában ez belekerülhet, de egyelőre várnék vele.
