### ISSUE TITLE
disable COD

### ISSUE THREAD

**Issue by rrd108** [webmenedzser/uvb-connector#4]
Azon gondolkoztam, hogy nem lenne-e jobb beállíthatóvá tenni, hogy a COD a threshold alatti usereknél meg se jelenjen / megjelenjen, de ne legyen kiválasztható.

Mert az emberünk jön a webshopba, utánvéttel vásárolna, nem jelenik meg az opció és telefonál, vagy ír, hogy miért nincs utánvét? Az ügyfélszolgálatos nem fogja tudni, hogy technikai hiba van, vagy problémás az ügyfél.

**Comment by Saboteur777** [comment]
Erre valószínűleg az a megoldás, hogy edukálni kell az ügyfélszolgálatosokat. 

A referencia implementációba én ezt a funkcionalitást képzeltem el, de pont azért van ez a connector library, hogy mindenki olyat működést alakítson ki magának, ami neki megfelelő.
