### ISSUE TITLE
UNAS support

### ISSUE THREAD

**Issue by rrd108** [webmenedzser/uvb-connector#5]
Itthon az unas a 2. legnépszerűbb webshop rendszer. Érdemes lenne megfontolni ennek az integrálását is. Én nem vagyok vele képben.

**Comment by Saboteur777** [comment]
Már felvettem velük a kapcsolatot, várom a válaszukat.

**Comment by Saboteur777** [comment]
Végre lezárhatom! :partying_face: 

![kép](https://github.com/webmenedzser/uvb-connector/assets/9061795/32c0aaaa-4042-473a-a745-a2962f8115e0)
