### ISSUE TITLE
woocommerce plugin empty order on error

### ISSUE THREAD

**Issue by rrd108** [webmenedzser/uvb-connector#7]
Volt egy rendelésünk aminél az uvb connector hibára futott:

Hiba a rendelés mentésekor. Server error: `POST https://utanvet-ellenor.hu/api/v1/signals/HASH` resulted in a `500 Internal Server Error` response:
An internal server error occurred.

A HASH-t átírtam.

Ennek hatására a rendelés létrejött, lehet látni a végösszeget, de nem lehet látni a termékeket.

**Comment by Saboteur777** [comment]
Szia! Ez mikor történt? Tegnap volt egy kisebb fennakadás (elfogyott a szerveren a hely... :\ ), ami internal server error-ban nyilvánult meg, azóta viszont helyre kellett állnia.

**Comment by rrd108** [comment]
tegnap 10:17-kor

Nem néztem a woocommerce plugin kódot, de ha kiüríti a kosarat 500-as hibánál akkor az lesz a gond.

**Comment by Saboteur777** [comment]
Igen, akkor már leállás volt. 

Viszont nem teljesen értem a hibajelenséget: ha a szerver (500-as) hibát ad vissza, akkor mi történik a shop oldalán?

**Comment by rrd108** [comment]
Úgy tűnik, hogy kiüríti aadmin oldalon a kosarat, a megrendelés létrejön, de termékek nélkül. Nálam pont egy paypalos fizetés volt, a paypal a végösszeget megkapta, de a termék listát nem. Nem is tudjuk mit kéne küldenünk...
Kijött a megrendelésről az email is, az is termékek nélkül egy végösszeggel.

**Comment by Saboteur777** [comment]
Hm... Amit tudok tenni, hogy megpróbálom reprodukálni, plusz beépítek védelmet arra az esetre, ha a szerver nem lenne elérhető.

**Comment by rrd108** [comment]
500-as hibát a legegyszerűbb úgy tesztelni, hogy a .htaccess-be beteszel valami értelmetlen szöveget. Az 500-at dob általában.

**Comment by Saboteur777** [comment]
nginx-et használok, szóval .htaccess nem jön szóba, de 500-as hibát tudok produkálni, abban profi vagyok. :D

**Comment by Saboteur777** [comment]
Fixed in aef0e2dd3bbc495a4b1eda8f896c50a49bbb71b5.
